### PR TITLE
create checkin page, add PWA installation, combine all pages into one SPA

### PR DESCRIPTION
**Pull request by jaminitaa**

### CODE REVIEW

**Review by denad00 — COMMENTED** [review]
this looks good to me! I'm gonna be updating the pre-recorded call files later today to include the new audio files

**Review by harshitpunn — COMMENTED** [review]
Looks good!

**Comment by denad00** [comment]
[index.html file in spa breaks whenever someone tries to add/change it](https://trello.com/c/RnmYNAqt/7-indexhtml-file-in-spa-breaks-whenever-someone-tries-to-add-change-it)

**Comment by denad00** [comment]
[Update script tags in html files](https://trello.com/c/TX3poJlE/6-update-script-tags-in-html-files)

**Comment by denad00** [comment]
[spa - combining files has broken a lot](https://trello.com/c/3AABwkeS/8-spa-combining-files-has-broken-a-lot)

**Pull request merged**
